display-name-zh: "复古都市赛璐璐短片"
version: 1.0.0
tag-cn: "电商 / 内容运营"
complete-tags-cn:
  - "动画"
  - "精选"
summary-cn: "90年代复古都市赛璐璐动画生成器，包含颗粒噪点、霓虹色调与CityPop氛围感镜头语言"
desc-cn: "90年代复古都市赛璐璐动画生成器，包含颗粒噪点、霓虹色调与CityPop氛围感镜头语言"
author-cn: "OmniMux"
source: official
